use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::helpers::deserialize_clearable;
use crate::node::{NodeEnvelope, ValidationError};

/// The `database-settings` schema's id and the key of its storage bucket.
pub const DATABASE_SETTINGS_NODE_TYPE: &str = "database-settings";

/// The fixed id of the settings singleton every database seeds. It differs
/// from the schema's id, which is the type's name.
pub const DATABASE_SETTINGS_NODE_ID: &str = "database-settings-singleton";

/// How much of a finished terminal session capture saves (ADR-095 §2).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "snake_case")]
pub enum CaptureContent {
    /// Agent type, start and end time, exit code and session id.
    #[default]
    MetadataOnly,
    /// Metadata plus a brief summary of the output.
    Summary,
    /// Metadata plus the full output transcript.
    Full,
}

impl CaptureContent {
    pub const ALL: [(CaptureContent, &'static str); 3] = [
        (CaptureContent::MetadataOnly, "Metadata only"),
        (CaptureContent::Summary, "Summary"),
        (CaptureContent::Full, "Full transcript"),
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::MetadataOnly => "metadata_only",
            Self::Summary => "summary",
            Self::Full => "full",
        }
    }
}

/// One OpenAI-compatible provider a database has configured (ADR-095 §2).
///
/// A nested stored value: snake_case keys, closed to keys it does not declare.
/// The API key is node data and travels with the config.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(deny_unknown_fields)]
pub struct ProviderConfig {
    /// UUID generated by the client that creates the config. Chats refer to
    /// the provider as `openai-compat:<id>`.
    pub id: String,
    /// Display name in the model selector. Never sent to the endpoint.
    pub name: String,
    /// Base URL of the endpoint; requests go to `<base_url>/chat/completions`.
    pub base_url: String,
    /// Sent as `Authorization: Bearer <api_key>`. Empty for endpoints that
    /// need no auth.
    #[serde(default)]
    pub api_key: String,
    /// The `model` field sent in chat-completions requests. Empty means the
    /// endpoint's own default.
    #[serde(default)]
    pub model: String,
    /// The routing-reliability probe's verdict per served model. A model that
    /// is absent was never probed. The verdicts describe the endpoint and
    /// model above, so a write that changes either drops them.
    #[serde(default)]
    pub routing_ok: BTreeMap<String, bool>,
}

/// The `database-settings` schema's fields, decoded from the node's
/// properties (ADR-095).
///
/// The only reader of a stored settings node: storage keys are the schema's
/// snake_case field names, hoisted by the store under
/// `properties.database-settings.*` and left there when another build retypes
/// the singleton to a subtype (ADR-083 §2). [`Self::from_properties`] reads
/// that bucket, or the flat shape a node built in memory carries. On the wire
/// the same fields travel camelCase at the top level of a
/// [`DatabaseSettingsNode`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct DatabaseSettingsFields {
    /// Ids of the extensions a reader needs in order to read this database.
    pub required_extensions: Vec<String>,
    /// Whether a finished terminal session is saved to its chat node.
    pub capture_enabled: bool,
    /// How much of a captured session is saved.
    pub capture_content: CaptureContent,
    /// The OpenAI-compatible providers this database has configured.
    pub providers: Vec<ProviderConfig>,
}

impl Default for DatabaseSettingsFields {
    /// The schema defaults: a new database captures nothing, serves no
    /// external tools and has no providers.
    fn default() -> Self {
        Self {
            required_extensions: Vec::new(),
            capture_enabled: false,
            capture_content: CaptureContent::default(),
            providers: Vec::new(),
        }
    }
}

impl DatabaseSettingsFields {
    /// Decode from properties in either the hoisted
    /// (`properties.database-settings.*`) or flat shape, preferring the bucket
    /// when there is one. An absent or `null` field takes the schema default;
    /// keys the schema does not declare are ignored.
    ///
    /// # Errors
    ///
    /// `InvalidProperties` naming the field, if one is present with the wrong
    /// shape: a list that is not strings, a value outside `capture_content`'s
    /// vocabulary, a provider with an unknown key, no id or an id that is not
    /// a UUID.
    pub fn from_properties(properties: &Value) -> Result<Self, ValidationError> {
        let bucket = properties
            .get(DATABASE_SETTINGS_NODE_TYPE)
            .filter(|b| b.is_object())
            .unwrap_or(properties);
        let field = |key: &str| bucket.get(key).filter(|v| !v.is_null());

        let providers: Vec<ProviderConfig> =
            decode(field("providers"), "providers")?.unwrap_or_default();
        if let Some(bad) = providers
            .iter()
            .find(|p| uuid::Uuid::parse_str(&p.id).is_err())
        {
            return Err(invalid(
                "providers",
                &format!("id '{}' is not a UUID", bad.id),
            ));
        }

        Ok(Self {
            required_extensions: decode(field("required_extensions"), "required_extensions")?
                .unwrap_or_default(),
            capture_enabled: decode(field("capture_enabled"), "capture_enabled")?.unwrap_or(false),
            capture_content: decode(field("capture_content"), "capture_content")?
                .unwrap_or_default(),
            providers,
        })
    }

    /// The provider with this id, if the database has configured it.
    pub fn provider(&self, id: &str) -> Option<&ProviderConfig> {
        self.providers.iter().find(|p| p.id == id)
    }
}

fn decode<T: serde::de::DeserializeOwned>(
    value: Option<&Value>,
    key: &str,
) -> Result<Option<T>, ValidationError> {
    value
        .map(|v| serde_json::from_value(v.clone()).map_err(|e| invalid(key, &e.to_string())))
        .transpose()
}

fn invalid(key: &str, detail: &str) -> ValidationError {
    ValidationError::InvalidProperties(format!("database-settings field '{key}': {detail}"))
}

/// Wire shape for the database-settings singleton sent to the frontend.
///
/// Produced by `node_to_typed_value` for a `database-settings` node: the
/// schema's fields are promoted to the top level (camelCase, see
/// [`DatabaseSettingsFields`]).
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct DatabaseSettingsNode {
    /// The fields every node carries. `properties` holds extension fields
    /// only; the type's own fields are the typed ones below.
    #[serde(flatten)]
    pub envelope: NodeEnvelope,
    #[serde(flatten)]
    pub fields: DatabaseSettingsFields,
}

/// Partial update for the settings node's core fields, received from the
/// frontend.
///
/// Every field is tri-state: absent leaves it unchanged, `null` clears it (it
/// then reads as its default), and a value replaces it whole. A provider list
/// is replaced as a list, never merged.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[cfg_attr(feature = "ts", ts(optional_fields))]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DatabaseSettingsNodeUpdate {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_clearable"
    )]
    pub required_extensions: Option<Option<Vec<String>>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_clearable"
    )]
    pub capture_enabled: Option<Option<bool>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_clearable"
    )]
    pub capture_content: Option<Option<CaptureContent>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_clearable"
    )]
    pub providers: Option<Option<Vec<ProviderConfig>>>,
}

impl DatabaseSettingsNodeUpdate {
    /// True when the update changes nothing.
    pub fn is_empty(&self) -> bool {
        self == &Self::default()
    }

    /// The flat, bare-key properties patch this update writes
    /// (`{"required_extensions": ["x"]}`); a cleared field is written as
    /// `null`. The service layer moves the keys into the `database-settings`
    /// storage bucket.
    pub fn to_properties_patch(&self) -> Value {
        let mut patch = serde_json::Map::new();
        fn put<T: Serialize>(
            patch: &mut serde_json::Map<String, Value>,
            key: &str,
            value: &Option<Option<T>>,
        ) {
            if let Some(value) = value {
                patch.insert(key.to_string(), serde_json::json!(value));
            }
        }
        put(&mut patch, "required_extensions", &self.required_extensions);
        put(&mut patch, "capture_enabled", &self.capture_enabled);
        put(&mut patch, "capture_content", &self.capture_content);
        put(&mut patch, "providers", &self.providers);
        Value::Object(patch)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    const ID: &str = "0b1c2d3e-4f50-4a6b-8c7d-9e0f1a2b3c4d";

    fn update(json: &str) -> Result<DatabaseSettingsNodeUpdate, serde_json::Error> {
        serde_json::from_str(json)
    }

    /// The update carries the settings schema's fields only; naming anything
    /// else is an error rather than a silently dropped write.
    #[test]
    fn an_unknown_key_is_rejected() {
        assert!(update(r#"{"content": "Settings"}"#).is_err());
    }

    #[test]
    fn each_field_rejects_the_wrong_type() {
        for body in [
            r#"{"requiredExtensions": [1]}"#,
            r#"{"captureEnabled": "yes"}"#,
            r#"{"captureContent": 3}"#,
            r#"{"providers": "none"}"#,
            r#"{"providers": [1]}"#,
        ] {
            assert!(update(body).is_err(), "{body} must be rejected");
        }
    }

    /// External tools are enabled by the client config `nodespace mcp install`
    /// writes, not by a database setting, so the typed update has no such key.
    #[test]
    fn the_typed_update_rejects_an_external_tools_key() {
        assert!(update(r#"{"externalToolsEnabled": true}"#).is_err());
    }

    #[test]
    fn capture_content_is_closed_to_its_vocabulary() {
        assert!(update(r#"{"captureContent": "everything"}"#).is_err());
        for (value, expected) in [
            ("metadata_only", CaptureContent::MetadataOnly),
            ("summary", CaptureContent::Summary),
            ("full", CaptureContent::Full),
        ] {
            let parsed = update(&format!(r#"{{"captureContent": "{value}"}}"#)).unwrap();
            assert_eq!(parsed.capture_content, Some(Some(expected)));
            assert_eq!(expected.as_str(), value);
        }
    }

    #[test]
    fn a_provider_config_is_closed_and_needs_an_id() {
        let ok = format!(
            r#"{{"providers": [{{"id": "{ID}", "name": "Local", "base_url": "http://x/v1"}}]}}"#
        );
        let parsed = update(&ok).unwrap();
        let providers = parsed.providers.unwrap().unwrap();
        assert_eq!(providers[0].api_key, "");
        assert!(providers[0].routing_ok.is_empty());

        let unknown_key = format!(
            r#"{{"providers": [{{"id": "{ID}", "name": "n", "base_url": "u", "extra": 1}}]}}"#
        );
        assert!(update(&unknown_key).is_err());
        let camel_case =
            format!(r#"{{"providers": [{{"id": "{ID}", "name": "n", "baseUrl": "u"}}]}}"#);
        assert!(update(&camel_case).is_err());
        let no_id = r#"{"providers": [{"name": "n", "base_url": "u"}]}"#;
        assert!(update(no_id).is_err());
    }

    #[test]
    fn absent_null_and_value_are_distinct() {
        let absent = update("{}").unwrap();
        assert!(absent.is_empty());
        assert_eq!(absent.to_properties_patch(), json!({}));

        let cleared = update(r#"{"requiredExtensions": null, "captureEnabled": null}"#).unwrap();
        assert_eq!(cleared.required_extensions, Some(None));
        assert_eq!(
            cleared.to_properties_patch(),
            json!({ "required_extensions": null, "capture_enabled": null })
        );

        let set = update(
            r#"{"requiredExtensions": ["fixture"], "captureEnabled": true,
                "captureContent": "full", "providers": []}"#,
        )
        .unwrap();
        assert_eq!(
            set.to_properties_patch(),
            json!({
                "required_extensions": ["fixture"],
                "capture_enabled": true,
                "capture_content": "full",
                "providers": [],
            })
        );
    }

    #[test]
    fn fields_read_the_bucket_or_the_flat_shape_and_default_when_absent() {
        let defaults = DatabaseSettingsFields::from_properties(&json!({})).unwrap();
        assert_eq!(defaults, DatabaseSettingsFields::default());

        let provider = json!({"id": ID, "name": "n", "base_url": "u", "routing_ok": {"m": false}});
        let bucketed = DatabaseSettingsFields::from_properties(&json!({
            "database-settings": {
                "capture_enabled": true,
                "capture_content": "summary",
                "providers": [provider],
            }
        }))
        .unwrap();
        assert!(bucketed.capture_enabled);
        assert_eq!(bucketed.capture_content, CaptureContent::Summary);
        assert!(!bucketed.provider(ID).unwrap().routing_ok["m"]);

        let flat = DatabaseSettingsFields::from_properties(&json!({
            "capture_enabled": true,
        }))
        .unwrap();
        assert!(flat.capture_enabled);
    }

    #[test]
    fn stored_fields_that_do_not_decode_are_named() {
        for properties in [
            json!({"capture_content": "all"}),
            json!({"providers": [{"id": "not-a-uuid", "name": "n", "base_url": "u"}]}),
            json!({"providers": [{"id": ID, "name": "n", "base_url": "u", "x": 1}]}),
            json!({"providers": [{"name": "n", "base_url": "u"}]}),
            json!({"required_extensions": "pro"}),
        ] {
            assert!(
                DatabaseSettingsFields::from_properties(&properties).is_err(),
                "{properties} must be rejected"
            );
        }
    }
}
