#!/usr/bin/env bun
// A private address for this OS user's own gate sccache server. sccache runs
// exactly one server per address; this machine (and others like it) is
// shared by more than one macOS account, each with its own clone and
// `.tools/`. A single shared address would mean whichever account's gate
// started the server first silently owned it, and every other account's
// gate would then compile through a server process running as the wrong OS
// user — one that can't write that account's `target/` or temp files, so
// compiles fail with permission errors.
//
// `tmpdir()` is macOS-private per account (`/var/folders/.../T/`, mode
// 0700, owned by the calling user) on the only platform sccache is set up
// for today (setup-rust-tooling.ts pins a darwin-arm64 release only). A
// future non-macOS sccache release would need this rechecked: `tmpdir()`
// there is often the shared, world-writable `/tmp`, where a predictable
// per-uid filename is no longer private on its own.
//
// A gate that died mid-run (crash, kill -9, power loss) can leave a stale
// socket file with no listener behind. Verified against the pinned sccache
// build that `--start-server` cleanly rebinds over a stale path — no manual
// cleanup needed.
import { tmpdir } from "node:os";
import { join } from "node:path";

/**
 * A unix domain socket path private to `uid`, for `SCCACHE_SERVER_UDS`.
 * Keying it on the numeric uid keeps every account's server apart from
 * every other account's, and gives each account a stable path across runs.
 */
export function sccacheServerUds(uid: number): string {
  return join(tmpdir(), `nodespace-gate-sccache-${uid}.sock`);
}

/** The compiler cache's size cap, for gate builds and development builds alike. */
export const SCCACHE_CACHE_SIZE = "20G";

/** First line of every file setup-rust-tooling.ts generates, so it can tell its own from a hand-written one. */
export const GENERATED_MARKER = "Generated by scripts/setup-rust-tooling.ts";

/**
 * The rustc wrapper development builds go through (setup-rust-tooling.ts
 * points cargo at it). A shell script because cargo runs it once per crate it
 * compiles. It hands sccache the settings test-gate.ts gives the gate's own
 * builds — the socket computed as sccacheServerUds() does, Bun's tmpdir()
 * being $TMPDIR without its trailing slash, else /tmp — so development builds
 * and merge gates share one server and one cache. Also the CMake compiler
 * launcher, so llama.cpp's C++ is cached too: invoked as `<wrapper> <compiler>
 * <args>`, exactly the shape sccache takes.
 */
export function devRustcWrapper(toolsDir: string): string {
  return `#!/bin/sh
# ${GENERATED_MARKER} on \`bun install\`; rewritten there, so don't edit.
tmp="\${TMPDIR:-/tmp}"
tmp="\${tmp%/}"
export SCCACHE_DIR="${join(toolsDir, "sccache-cache")}"
export SCCACHE_CACHE_SIZE="${SCCACHE_CACHE_SIZE}"
export SCCACHE_SERVER_UDS="$tmp/nodespace-gate-sccache-$(id -u).sock"
exec "${join(toolsDir, "bin", "sccache")}" "$@"
`;
}

/**
 * The checkout's `.cargo/config.toml` (gitignored): every cargo command in
 * the checkout — including a bare `cargo check` — compiles through the
 * wrapper. Across checkouts that shares llama.cpp's C/C++ objects; Rust
 * crates hit only within the checkout's own target dir (see
 * setup-rust-tooling.ts). Workspace crates keep incremental compilation,
 * which sccache passes through uncached, so the edit loop is unchanged. The
 * gate's own RUSTC_WRAPPER and CMake variables take precedence over this file.
 */
export function devCargoConfig(wrapper: string): string {
  return `# ${GENERATED_MARKER} on \`bun install\`; rewritten there, so don't edit.
# Every cargo build here goes through the repository's sccache, which shares
# llama.cpp's C/C++ build across checkouts. Opt out with
# NODESPACE_SKIP_RUST_TOOLING=1 and delete this file.
[build]
rustc-wrapper = "${wrapper}"

[env]
CMAKE_C_COMPILER_LAUNCHER = "${wrapper}"
CMAKE_CXX_COMPILER_LAUNCHER = "${wrapper}"
`;
}
